import {
  PatientOrderRow,
  Order,
  PatientDetails,
} from '../models/orderFulfillment';

const createOrder = (
  id: string,
  orderName: string,
  priority: 'Routine' | 'Urgent',
  status: 'New' | 'In Progress' | 'Acknowledged',
  provider: string,
  dateTime: string,
  owner: string | null,
  providerComments?: string,
  patient?: PatientDetails,
): Order => ({
  id,
  orderName,
  orderType: 'Rehab Order',
  priority,
  status,
  provider,
  dateTime,
  owner,
  providerComments,
  patient,
});

export const rehabOrdersMockData: PatientOrderRow[] = [
  {
    id: 'patient-1',
    patientName: 'David Kamau',
    identifier: 'CRK262350',
    recentOrdersCount: 1,
    totalOrdersCount: 3,
    urgentCount: 1,
    isExpandable: true,
    orders: [
      createOrder(
        'order-1-1',
        'New Cast - Plaster',
        'Urgent',
        'New',
        'Mike Ronoh',
        '12 Nov 25 04:24 PM',
        null,
        'Post-operative X-ray for assessing healing or implant position | Monitoring of progress for alignment / comparative purposes | High Risk | Request from ward | Request from clinic | Pre-operative X-ray for diagnostic or planning purposes',
        {
          age: '8 years 11 months 8 days',
          dateOfBirth: '09 Jan 2017',
          gender: 'Male',
          address: '123 Nairobi St, Kenya',
          phoneNumber: '+254 700 123 456',
        },
      ),
      createOrder(
        'order-1-2',
        'Rehab Therapy - Limb',
        'Routine',
        'In Progress',
        'Mike Ronoh',
        '12 Nov 25 04:24 PM',
        'Ted Okatch',
        'Continue rehabilitation exercises focusing on range of motion and strength building.',
      ),
      createOrder(
        'order-1-3',
        'New Cast - Plaster',
        'Routine',
        'Acknowledged',
        'Mike Ronoh',
        '12 Nov 25 04:24 PM',
        'Ted Okatch',
      ),
    ],
  },
  {
    id: 'patient-2',
    patientName: 'Samuel Mensah',
    identifier: 'CRK266785',
    recentOrdersCount: 2,
    totalOrdersCount: 4,
    urgentCount: 2,
    isExpandable: true,
    orders: [
      createOrder(
        'order-2-1',
        'Physiotherapy Evaluation',
        'Urgent',
        'New',
        'Sarah Kimani',
        '12 Nov 25 03:15 PM',
        null,
        'Patient requires comprehensive physiotherapy evaluation for lower limb mobility issues.',
      ),
      createOrder(
        'order-2-2',
        'Occupational Therapy',
        'Urgent',
        'New',
        'Sarah Kimani',
        '12 Nov 25 03:15 PM',
        null,
        'Assessment needed for activities of daily living and adaptive equipment recommendations.',
      ),
      createOrder(
        'order-2-3',
        'Mobility Assessment',
        'Routine',
        'In Progress',
        'Sarah Kimani',
        '12 Nov 25 02:30 PM',
        'Jane Wanjiku',
      ),
      createOrder(
        'order-2-4',
        'Prosthetic Fitting',
        'Routine',
        'Acknowledged',
        'Sarah Kimani',
        '12 Nov 25 01:00 PM',
        'Jane Wanjiku',
      ),
    ],
  },
  {
    id: 'patient-3',
    patientName: 'Test Patient ABC',
    identifier: 'CRK265423',
    recentOrdersCount: 0,
    totalOrdersCount: 4,
    urgentCount: 0,
    isExpandable: true,
    orders: [
      createOrder(
        'order-3-1',
        'Gait Training',
        'Routine',
        'In Progress',
        'Dr. Amara Okonkwo',
        '11 Nov 25 10:00 AM',
        'Peter Mutua',
      ),
      createOrder(
        'order-3-2',
        'Balance Assessment',
        'Routine',
        'Acknowledged',
        'Dr. Amara Okonkwo',
        '11 Nov 25 09:30 AM',
        'Peter Mutua',
      ),
      createOrder(
        'order-3-3',
        'Strength Training',
        'Routine',
        'Acknowledged',
        'Dr. Amara Okonkwo',
        '10 Nov 25 02:00 PM',
        'Peter Mutua',
      ),
      createOrder(
        'order-3-4',
        'Range of Motion',
        'Routine',
        'Acknowledged',
        'Dr. Amara Okonkwo',
        '10 Nov 25 11:00 AM',
        'Peter Mutua',
      ),
    ],
  },
  {
    id: 'patient-4',
    patientName: 'Test Patient XYZ',
    identifier: 'CRK260972',
    recentOrdersCount: 0,
    totalOrdersCount: 3,
    urgentCount: 0,
    isExpandable: true,
    orders: [
      createOrder(
        'order-4-1',
        'Hydrotherapy',
        'Routine',
        'In Progress',
        'Dr. Fatou Diallo',
        '10 Nov 25 03:00 PM',
        'Mary Achieng',
      ),
      createOrder(
        'order-4-2',
        'Electrotherapy',
        'Routine',
        'Acknowledged',
        'Dr. Fatou Diallo',
        '10 Nov 25 01:30 PM',
        'Mary Achieng',
      ),
      createOrder(
        'order-4-3',
        'Massage Therapy',
        'Routine',
        'Acknowledged',
        'Dr. Fatou Diallo',
        '09 Nov 25 04:00 PM',
        'Mary Achieng',
      ),
    ],
  },
  {
    id: 'patient-5',
    patientName: 'John Doe',
    identifier: 'CRK262342',
    recentOrdersCount: 0,
    totalOrdersCount: 2,
    urgentCount: 0,
    isExpandable: true,
    orders: [
      createOrder(
        'order-5-1',
        'Rehabilitation Assessment',
        'Routine',
        'Acknowledged',
        'Dr. Kofi Asante',
        '08 Nov 25 11:00 AM',
        'Grace Nyambura',
      ),
      createOrder(
        'order-5-2',
        'Exercise Program',
        'Routine',
        'Acknowledged',
        'Dr. Kofi Asante',
        '08 Nov 25 10:00 AM',
        'Grace Nyambura',
      ),
    ],
  },
  {
    id: 'patient-6',
    patientName: 'Melody Sunshine',
    identifier: 'CRK261234',
    recentOrdersCount: 0,
    totalOrdersCount: 3,
    urgentCount: 0,
    isExpandable: true,
    orders: [
      createOrder(
        'order-6-1',
        'Speech Therapy',
        'Routine',
        'In Progress',
        'Dr. Nadia Hassan',
        '07 Nov 25 02:00 PM',
        'Samuel Ochieng',
      ),
      createOrder(
        'order-6-2',
        'Cognitive Rehab',
        'Routine',
        'Acknowledged',
        'Dr. Nadia Hassan',
        '07 Nov 25 11:30 AM',
        'Samuel Ochieng',
      ),
      createOrder(
        'order-6-3',
        'Swallowing Assessment',
        'Routine',
        'Acknowledged',
        'Dr. Nadia Hassan',
        '06 Nov 25 03:00 PM',
        'Samuel Ochieng',
      ),
    ],
  },
];

export const radiologyOrdersMockData: PatientOrderRow[] = [
  {
    id: 'patient-r-1',
    patientName: 'Alice Njeri',
    identifier: 'CRK270001',
    recentOrdersCount: 1,
    totalOrdersCount: 2,
    urgentCount: 1,
    isExpandable: true,
    orders: [
      createOrder(
        'order-r-1-1',
        'X-Ray Chest',
        'Urgent',
        'New',
        'Dr. James Mwangi',
        '12 Nov 25 05:00 PM',
        null,
      ),
      createOrder(
        'order-r-1-2',
        'CT Scan - Head',
        'Routine',
        'In Progress',
        'Dr. James Mwangi',
        '12 Nov 25 04:00 PM',
        'Paul Kibet',
      ),
    ],
  },
  {
    id: 'patient-r-2',
    patientName: 'Bernard Ochieng',
    identifier: 'CRK270002',
    recentOrdersCount: 0,
    totalOrdersCount: 1,
    urgentCount: 0,
    isExpandable: true,
    orders: [
      createOrder(
        'order-r-2-1',
        'MRI - Spine',
        'Routine',
        'Acknowledged',
        'Dr. Lucy Wambui',
        '11 Nov 25 09:00 AM',
        'Diana Moraa',
      ),
    ],
  },
];

export const laboratoryOrdersMockData: PatientOrderRow[] = [
  {
    id: 'patient-l-1',
    patientName: 'Christine Auma',
    identifier: 'CRK280001',
    recentOrdersCount: 2,
    totalOrdersCount: 3,
    urgentCount: 1,
    isExpandable: true,
    orders: [
      createOrder(
        'order-l-1-1',
        'Complete Blood Count',
        'Urgent',
        'New',
        'Dr. Eric Otieno',
        '12 Nov 25 06:00 PM',
        null,
      ),
      createOrder(
        'order-l-1-2',
        'Liver Function Test',
        'Routine',
        'New',
        'Dr. Eric Otieno',
        '12 Nov 25 05:30 PM',
        null,
      ),
      createOrder(
        'order-l-1-3',
        'Urinalysis',
        'Routine',
        'In Progress',
        'Dr. Eric Otieno',
        '12 Nov 25 04:00 PM',
        'Faith Wangari',
      ),
    ],
  },
];

export const drugOrdersMockData: PatientOrderRow[] = [
  {
    id: 'patient-d-1',
    patientName: 'Emmanuel Kiprop',
    identifier: 'CRK290001',
    recentOrdersCount: 0,
    totalOrdersCount: 0,
    urgentCount: 0,
    isExpandable: false,
    orders: [],
  },
  {
    id: 'patient-d-2',
    patientName: 'Fatuma Hassan',
    identifier: 'CRK290002',
    recentOrdersCount: 0,
    totalOrdersCount: 0,
    urgentCount: 0,
    isExpandable: false,
    orders: [],
  },
];

export const prostheticAndOrthoticOrdersMockData: PatientOrderRow[] = [
  {
    id: 'patient-po-1',
    patientName: 'George Kamau',
    identifier: 'CRK300001',
    recentOrdersCount: 1,
    totalOrdersCount: 2,
    urgentCount: 0,
    isExpandable: true,
    orders: [
      createOrder(
        'order-po-1-1',
        'Prosthetic Limb Assessment',
        'Routine',
        'New',
        'Dr. Helen Mutiso',
        '12 Nov 25 03:00 PM',
        null,
      ),
      createOrder(
        'order-po-1-2',
        'Orthotic Fitting',
        'Routine',
        'In Progress',
        'Dr. Helen Mutiso',
        '12 Nov 25 01:00 PM',
        'Isaac Oduya',
      ),
    ],
  },
];

export const mockDataByTabLabel: Record<string, PatientOrderRow[]> = {
  'Radiology Order': radiologyOrdersMockData,
  'Lab Order': laboratoryOrdersMockData,
  'Drug Order': drugOrdersMockData,
  'IPD Drug Order': drugOrdersMockData,
  'Rehab Order': rehabOrdersMockData,
  'P&O Order': prostheticAndOrthoticOrdersMockData,
};

export const getTabCount = (tabLabel: string): number => {
  const data = mockDataByTabLabel[tabLabel];
  return data ? data.length : 0;
};

export const availableProviders = [
  { id: 'provider1', name: 'Dr. Smith' },
  { id: 'provider2', name: 'Dr. Johnson' },
  { id: 'provider3', name: 'Dr. Williams' },
  { id: 'provider4', name: 'Mike Ronoh' },
  { id: 'provider5', name: 'Ted Okatch' },
];
